# Generated by Django 4.2.4 on 2023-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='upload_file',
            field=models.FileField(unique=True, upload_to='', verbose_name='File'),
        ),
    ]
