# Generated by Django 4.2.4 on 2023-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_alter_filemodel_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_content',
            field=models.BinaryField(null=True),
        ),
    ]
