# Generated by Django 4.2.4 on 2023-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_filemodel_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_content',
            field=models.CharField(editable=False, null=True),
        ),
    ]
